In [1]:
import pandas as pd
import numpy as np
import warnings
import time
from datetime import datetime, timedelta, date
warnings.filterwarnings('ignore')
import os
pd.options.display.max_columns = 500
pd.options.display.max_rows = 500
from dateutil.relativedelta import relativedelta
from numpy import concatenate as cct
import glob

In [2]:
import openpyxl

In [3]:
path = os.getcwd()

In [4]:
path

'C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\\TermLoans Code_Dummy'

In [5]:
df_lendingkart = pd.read_csv(path+'\\LK\\LK.csv')

In [6]:
df_lendingkart.head()

,application_id,leadid,cls_app_id,email_id,mobile_number,created_by,SubDSA Details,customer_name,unique_id,app_created_date,app_modified_date,lead_source,created_by.1,company_name,regitration_type,industry,pincode,city,state,revenuerange,age_of_business,delivery_method,application_type,product_type,desired_amount,cibil_status,Status,Substatus,Rejection_reason,terms_sent_date,terms_amount,interest_rate,interest_rate_type,terms_tenure,processing_fess,insurer_name,insurance_amount,loan_amount,FI_Status,FI_Substatus,acceptance_status,acceptance_reason,risk_status,agreement_generated_date,agreement_sent_date,agreement_status,agreement_sent_by,courier_company_name,disbursal_date,disbursed_interest_rate,disbursed_amount,disbursed_tenure,first_installment_date
0,LAI-119474475,32601936,LAI-119474475,maimunaenterprisesog@gmail.com,9.822534e+09,PineLabs_Direct,NaN,Izhar Ali,64ea0ad754f900985d5290d7,26-08-2023,11-11-2023,PineLabs_Direct,PineLabs_Direct,MAIMUNA ENTERPRISES,Proprietorship,White goods-Electronic Appliances,440018.0,NAGPUR,MAHARASHTRA,1 - 10 Crores,More than 5 Years,Regular,New,Term Loan,750000,ACCEPTED,Disbursed,Disbursed,NaN,08-11-2023,988000.0,1.45,Flat,36.0,51058.0,ICICI-Income Suraksha,30762.0,988000.0,NaN,NaN,Disbursed,NaN,Approved,09-11-2023,NaN,Disbursed,NaN,NaN,11-11-2023,17.4,988000.0,36.0,15-12-2023
1,LAI-120459002,34049322,LAI-120459002,akashingole8007@gmail.com,8.007892e+09,PineLabs_Direct,NaN,Akash Ingole,6543b0a453a8c4c16c68c8b5,05-11-2023,11-11-2023,PineLabs_Direct,PineLabs_Direct,HOTEL MARATHA,Proprietorship,Restaurant & Hospitality,431001.0,AURANGABAD,MAHARASHTRA,1 - 10 Crores,More than 5 Years,Pending,New,Term Loan,1500000,ACCEPTED,Disbursed,Disbursed,NaN,10-11-2023,418000.0,1.40,Flat,36.0,23328.0,ICICI-Income Suraksha,13916.0,418000.0,NaN,NaN,Disbursed,NaN,Approved,11-11-2023,NaN,Disbursed,NaN,NaN,11-11-2023,16.8,418000.0,36.0,15-12-2023
2,LAI-120537585,34159809,LAI-120537585,saurabhagrawal7090@gmail.com,7.895085e+09,PineLabs_Direct,NaN,Saurabh Agrawal,654e537127c67e891e499323,10-11-2023,11-11-2023,PineLabs_Direct,PineLabs_Direct,M.S.FASHIONS,Proprietorship,Apparels;Clothing & Accessories,302004.0,JAIPUR,RAJASTHAN,12 - 30 Lacs,More than 5 Years,Pending,New,Term Loan,100000,ACCEPTED,Application in Progress,Application Details Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LAI-120007964,33422247,LAI-120007964,nhusain7371@gmail.com,8.896487e+09,Abhijeet Rathore,NaN,Mohd Nasir Husain,NaN,09-10-2023,11-11-2023,PineLabs_Direct,Abhijeet Rathore,M/S HUSAIN TELECOM,Proprietorship,Computers;Mobile & related Accessories,272175.0,KHALILABAD,UTTAR PRADESH,60 Lacs - 1 Crore,1 to 5 Years,Pending,New,Term Loan,0,ACCEPTED,Application Rejected,Reject - Expired,Application Expired-Dedupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,LAI-120477620,34077524,LAI-120477620,ranvijaysingh2324@gmail.com,8.630255e+09,PineLabs_Direct,NaN,Ranvijay Singh,NaN,06-11-2023,11-11-2023,PineLabs_Direct,PineLabs_Direct,NaN,Proprietorship,White goods-Electronic Appliances,NaN,NaN,NaN,30 - 60 Lacs,1 to 5 Years,Regular,New,Term Loan,0,ACCEPTED,Application Rejected,Reject - Lead,Not Registered Business,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_lendingkart['app_created_date'] = df_lendingkart['app_created_date'].str.slice(6,10)+'-'+df_lendingkart['app_created_date'].str.slice(3,5)+'-'+df_lendingkart['app_created_date'].str.slice(0,2)

In [8]:
df_lendingkart['disbursal_date'] = df_lendingkart['disbursal_date'].str.slice(6,10)+'-'+df_lendingkart['disbursal_date'].str.slice(3,5)+'-'+df_lendingkart['disbursal_date'].str.slice(0,2)

In [9]:
df_lendingkart['terms_sent_date'] = df_lendingkart['terms_sent_date'].str.slice(6,10)+'-'+df_lendingkart['terms_sent_date'].str.slice(3,5)+'-'+df_lendingkart['terms_sent_date'].str.slice(0,2)

In [10]:
df_lendingkart['app_created_date'].dtype

dtype('O')

In [11]:
df_lendingkart['disbursal_date'].dtype

dtype('O')

In [12]:
df_lendingkart.sample(5)

,application_id,leadid,cls_app_id,email_id,mobile_number,created_by,SubDSA Details,customer_name,unique_id,app_created_date,app_modified_date,lead_source,created_by.1,company_name,regitration_type,industry,pincode,city,state,revenuerange,age_of_business,delivery_method,application_type,product_type,desired_amount,cibil_status,Status,Substatus,Rejection_reason,terms_sent_date,terms_amount,interest_rate,interest_rate_type,terms_tenure,processing_fess,insurer_name,insurance_amount,loan_amount,FI_Status,FI_Substatus,acceptance_status,acceptance_reason,risk_status,agreement_generated_date,agreement_sent_date,agreement_status,agreement_sent_by,courier_company_name,disbursal_date,disbursed_interest_rate,disbursed_amount,disbursed_tenure,first_installment_date
3827,LAI-121675017,35943455,LAI-121675017,vkadiwala229@gmail.com,9.033253e+09,PineLabs_Direct,NaN,Saddam meman,65c39048c30ec1bd8443f48b,2024-02-07,07-02-2024,PineLabs_Direct,PineLabs_Direct,PERFECT SALES CORPORATION,Proprietorship,NaN,383001.0,Sabarkantha,GUJARAT,1 - 10 Crores,More than 5 Years,Pending,New,Term Loan,1500000,REJECTED,Application Rejected,Reject - Lead,CIBIL overdue in past loan;CIBIL overdue in cu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1156,LAI-120525375,34143539,LAI-120525375,naveenjuneja2121@gmail.com,9.914392e+09,PineLabs_Direct,NaN,Naveen Kumar,6521f8772278cbddbfb5e5bd,2023-11-09,11-12-2023,PineLabs_Direct,PineLabs_Direct,M/S VASDEV CYCLE WORKS,Proprietorship,Industrial Supplies & Solutions,140501.0,PUN,PUNJAB,1 - 10 Crores,More than 5 Years,Pending,New,Term Loan,1000000,ACCEPTED,Application in Progress,Not Started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3038,LAI-117860949,29972726,LAI-117860949,pummytelecom58@gmail.com,9.999980e+09,PineLabs_Direct,NaN,Sandeep Kumar,NaN,2023-05-08,20-01-2024,PineLabs_Direct,PineLabs_Direct,PUMMY TELECOM,Proprietorship,Computers;Mobile & related Accessories,110083.0,WEST DELHI,DELHI,60 Lacs - 1 Crore,More than 5 Years,Pending,New,Term Loan,0,ACCEPTED,Application Rejected,Reject - By Customer,Client not responding/ not interested,2023-05-11,427406.0,1.62,Declining Balance,36.0,12608.0,NaN,0.0,427406.0,NaN,NaN,Terms Non-Moving,Application Rejected,NaN,NaN,NaN,Application Rejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3615,LAI-121523117,35722893,LAI-121523117,bhatisahil455@gmail.com,9.667473e+09,PineLabs_Direct,NaN,Sahil Rangreg,64c35bfa40d07751c2436174,2024-01-27,03-02-2024,PineLabs_Direct,PineLabs_Direct,SAHIL RANGREJ,Proprietorship,Apparels;Clothing & Accessories,311404.0,Bhilwara,RAJASTHAN,12 - 30 Lacs,More than 5 Years,Regular,New,Term Loan,150000,ACCEPTED,Application in Progress,Application Details Incomplete,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3325,LAI-119108341,31994941,LAI-119108341,narayandaschabra1985@gmail.com,7.999111e+09,PineLabs_Direct,NaN,Narayan Chabra,64c5270840d07751c243a8ab,2023-07-29,28-01-2024,PineLabs_Direct,PineLabs_Direct,NaN,Proprietorship,NaN,474001.0,NaN,NaN,12 - 30 Lacs,More than 5 Years,Regular,New,Term Loan,100000,ACCEPTED,Application Rejected,Reject - Expired,Application Expired-Dedupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_lendingkart['Customer ID'] = df_lendingkart['leadid']
df_lendingkart['LAN'] = df_lendingkart['application_id']
df_lendingkart['Contact No.'] = df_lendingkart['mobile_number']
df_lendingkart['Lender Partner '] = 'Lending Kart'
df_lendingkart['Merchant Name '] = df_lendingkart['customer_name']
df_lendingkart['Business Name '] = df_lendingkart['company_name']
df_lendingkart['Region'] = ''
df_lendingkart['State'] = df_lendingkart['state']
df_lendingkart['City'] = df_lendingkart['city']
df_lendingkart['Final Lead Status'] = df_lendingkart['Status']
df_lendingkart['Lead Created Date'] = df_lendingkart['app_created_date']
df_lendingkart['Lead last Disposition '] = df_lendingkart['Substatus']
df_lendingkart['Last disposition Date'] = df_lendingkart['app_modified_date']
df_lendingkart['Pendency'] = df_lendingkart['acceptance_status']
df_lendingkart['Monthly turn over of merchant'] = df_lendingkart['revenuerange']
df_lendingkart['Loan Amount Requested'] = df_lendingkart['desired_amount']
df_lendingkart['Sanctioned Amount'] = df_lendingkart['terms_amount']
df_lendingkart['PF Charges'] = df_lendingkart['processing_fess']
df_lendingkart['Doc Charges'] = ''
df_lendingkart['Insurance Charges'] = df_lendingkart['insurance_amount']
df_lendingkart['Net Disbursed Amount'] = df_lendingkart['disbursed_amount']
df_lendingkart['Interest Rate'] = df_lendingkart['interest_rate']
df_lendingkart['Interest Rate Type'] = df_lendingkart['interest_rate_type']
df_lendingkart['Tenure'] = df_lendingkart['terms_tenure']
df_lendingkart['Repayment Frequency'] = ''
df_lendingkart['Approved Date'] = df_lendingkart['terms_sent_date']
df_lendingkart['Disbursed Date'] = df_lendingkart['disbursal_date']
df_lendingkart['Post Sanctioned Status'] = df_lendingkart['acceptance_reason']
df_lendingkart['Rejected Reason'] = df_lendingkart['Rejection_reason']

In [14]:
df_lendingkart.columns

Index(['application_id', 'leadid', 'cls_app_id', 'email_id', 'mobile_number',
       'created_by', 'SubDSA Details', 'customer_name', 'unique_id',
       'app_created_date', 'app_modified_date', 'lead_source', 'created_by.1',
       'company_name', 'regitration_type', 'industry', 'pincode', 'city',
       'state', 'revenuerange', 'age_of_business', 'delivery_method',
       'application_type', 'product_type', 'desired_amount', 'cibil_status',
       'Status', 'Substatus', 'Rejection_reason', 'terms_sent_date',
       'terms_amount', 'interest_rate', 'interest_rate_type', 'terms_tenure',
       'processing_fess', 'insurer_name', 'insurance_amount', 'loan_amount',
       'FI_Status', 'FI_Substatus', 'acceptance_status', 'acceptance_reason',
       'risk_status', 'agreement_generated_date', 'agreement_sent_date',
       'agreement_status', 'agreement_sent_by', 'courier_company_name',
       'disbursal_date', 'disbursed_interest_rate', 'disbursed_amount',
       'disbursed_tenure', 'first_installment_date', 'Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason'],
      dtype='object')

In [15]:
df_lendingkart.dtypes

application_id                    object
leadid                             int64
cls_app_id                        object
email_id                          object
mobile_number                    float64
created_by                        object
SubDSA Details                   float64
customer_name                     object
unique_id                         object
app_created_date                  object
app_modified_date                 object
lead_source                       object
created_by.1                      object
company_name                      object
regitration_type                  object
industry                          object
pincode                          float64
city                              object
state                             object
revenuerange                      object
age_of_business                   object
delivery_method                   object
application_type                  object
product_type                      object
desired_amount                     int64
cibil_status                      object
Status                            object
Substatus                         object
Rejection_reason                  object
terms_sent_date                   object
terms_amount                     float64
interest_rate                    float64
interest_rate_type                object
terms_tenure                     float64
processing_fess                  float64
insurer_name                      object
insurance_amount                 float64
loan_amount                      float64
FI_Status                         object
FI_Substatus                     float64
acceptance_status                 object
acceptance_reason                 object
risk_status                       object
agreement_generated_date          object
agreement_sent_date               object
agreement_status                  object
agreement_sent_by                 object
courier_company_name             float64
disbursal_date                    object
disbursed_interest_rate          float64
disbursed_amount                 float64
disbursed_tenure                 float64
first_installment_date            object
Customer ID                        int64
LAN                               object
Contact No.                      float64
Lender Partner                    object
Merchant Name                     object
Business Name                     object
Region                            object
State                             object
City                              object
Final Lead Status                 object
Lead Created Date                 object
Lead last Disposition             object
Last disposition Date             object
Pendency                          object
Monthly turn over of merchant     object
Loan Amount Requested              int64
Sanctioned Amount                float64
PF Charges                       float64
Doc Charges                       object
Insurance Charges                float64
Net Disbursed Amount             float64
Interest Rate                    float64
Interest Rate Type                object
Tenure                           float64
Repayment Frequency               object
Approved Date                     object
Disbursed Date                    object
Post Sanctioned Status            object
Rejected Reason                   object
dtype: object

In [16]:
df_flexiloansA = pd.read_excel(path+'\\FL\\FL.xlsx',sheet_name='approved',engine='openpyxl')

In [17]:
df_flexiloansA['Customer ID'] = df_flexiloansA['code']
df_flexiloansA['LAN'] = df_flexiloansA['number']
df_flexiloansA['Contact No.'] = df_flexiloansA['Mobile_no']
df_flexiloansA['Lender Partner '] = 'Flexi Loan'
df_flexiloansA['Merchant Name '] = ''
df_flexiloansA['Business Name '] = df_flexiloansA['business_name']
df_flexiloansA['Region'] = ''
df_flexiloansA['State'] = ''
df_flexiloansA['City'] = ''
df_flexiloansA['Final Lead Status'] = df_flexiloansA['s1']
df_flexiloansA['Lead Created Date'] = df_flexiloansA['Created']
df_flexiloansA['Lead last Disposition '] = df_flexiloansA['s3']
df_flexiloansA['Last disposition Date'] = ''
df_flexiloansA['Pendency'] = ''
df_flexiloansA['Monthly turn over of merchant'] = ''
df_flexiloansA['Loan Amount Requested'] = df_flexiloansA['Loan Amount']
df_flexiloansA['Sanctioned Amount'] = df_flexiloansA['Sanctioned Amount']
df_flexiloansA['PF Charges'] = df_flexiloansA['Pf Charges']
df_flexiloansA['Doc Charges'] = df_flexiloansA['Doc Charges']
df_flexiloansA['Insurance Charges'] = ''
df_flexiloansA['Net Disbursed Amount'] = df_flexiloansA['Net Disbursed Amount']
df_flexiloansA['Interest Rate'] = df_flexiloansA['Interest Rate']
df_flexiloansA['Interest Rate Type'] = df_flexiloansA['Interest Rate Type']
df_flexiloansA['Tenure'] = df_flexiloansA['Tenure']
df_flexiloansA['Repayment Frequency'] = df_flexiloansA['Repayment Frequency']
df_flexiloansA['Approved Date'] = df_flexiloansA['Approved Date']
df_flexiloansA['Disbursed Date'] = df_flexiloansA['Disbursed Date']
df_flexiloansA['Post Sanctioned Status'] = ''
df_flexiloansA['Rejected Reason'] = ''

In [18]:
df_flexiloansI = pd.read_excel(path+'\\FL\\FL.xlsx',sheet_name='In_progress',engine='openpyxl')

In [19]:
df_flexiloansI.head()

,code,business_name,application_no,partner_application_number,lead_code,Created,Hot Lead Date,Post_PD_date,Days Since Lead Created,Loan Amount,Total Calls Made,Calls Not Answered,Fresh_Top_Up,s1,s2,s3,Pending Documents,Pending Document Count,Priority,Document_Link,name,platform,MTO,serviceable,Mobile_no,inserted_on
0,65b9fec1axwci,MOBILE MALL,PEF-TAMAD-000-JAN24-00050,65b8fede8970297ad1f76b15,64d11f11ky5yu,2024-01-31,2024-02-05 13:16:36,2024-02-06 17:45:17,0,500000,25,6,Fresh,In Progress,Hot Lead,Post PD Hold,We found the following issue(s) with the banki...,3,1,http://apply.flexiloans.com/?al=true&lm=64d11f...,Pine Labs,Web,1000000.0,1,9655222238,2024-02-08 03:30:13.418
1,65bcda77g3gg8,SAHIL MOBILE,PEF-PUCHI-000-FEB24-00003,NaN,648168a943p3b,2024-02-02,2024-02-07 18:32:33,NaT,0,1000000,12,10,Fresh,In Progress,Hot Lead,Analysis Pending,We found the following issue(s) with the banki...,3,1,http://apply.flexiloans.com/?al=true&lm=648168...,Pine Labs,Manual Upload,1500000.0,1,9988819995,2024-02-08 03:30:13.418
2,65bdef81ys6zg,DANISH & COMPANY,PNF-UTBIR-000-FEB24-00008,NaN,65bdef818ubyn,2024-02-03,2024-02-06 16:13:18,NaT,0,2500000,25,22,Fresh,In Progress,Hot Lead,POST PD Document Pending,\nAdditional documents\nDocuments for 'Bank st...,8,1,http://apply.flexiloans.com/?al=true&lm=65bdef...,Pine Labs,Web,1000000.0,0,7905107714,2024-02-08 03:30:13.418
3,65c0f534sz8c1,KRISHNA MOBILE ACCESSORIES AND ELECTRONICS,PEF-MABAG-000-FEB24-00018,65c0efbb5cdb1822b782751d,65aca6164aubq,2024-02-05,2024-02-07 11:36:30,NaT,0,2000000,4,2,Fresh,In Progress,Hot Lead,PD,"Documents for 'KYC'\nOptional, any 1:\nPAN Car...",3,1,http://apply.flexiloans.com/?al=true&lm=65aca6...,Pine Labs,Web,1000000.0,0,8085665629,2024-02-08 03:30:13.418
4,65c1cad72a172,JYOTI PHARMACY,DEF-RAR.H-000-FEB24-00002,NaN,64a647b12sd8q,2024-02-06,2024-02-06 11:58:08,2024-02-06 16:38:44,0,600000,4,0,Fresh,In Progress,Hot Lead,Post PD Hold,We found the following issue(s) with the banki...,3,1,http://apply.flexiloans.com/?al=true&lm=64a647...,Pine Labs,Bulk upload,500000.0,1,9728321132,2024-02-08 03:30:13.418

In [20]:
df_flexiloansI['Customer ID'] = df_flexiloansI['code']
df_flexiloansI['LAN'] = df_flexiloansI['application_no']
df_flexiloansI['Contact No.'] = df_flexiloansI['Mobile_no']
df_flexiloansI['Lender Partner '] = 'Flexi Loan'
df_flexiloansI['Merchant Name '] = ''
df_flexiloansI['Business Name '] = df_flexiloansI['business_name']
df_flexiloansI['Region'] = ''
df_flexiloansI['State'] = ''
df_flexiloansI['City'] = ''
df_flexiloansI['Final Lead Status'] = df_flexiloansI['s2']
df_flexiloansI['Lead Created Date'] = df_flexiloansI['Created']
df_flexiloansI['Lead last Disposition '] = df_flexiloansI['s3']
df_flexiloansI['Last disposition Date'] = ''
df_flexiloansI['Pendency'] = df_flexiloansI['Pending Documents']
df_flexiloansI['Monthly turn over of merchant'] = ''
df_flexiloansI['Loan Amount Requested'] = df_flexiloansI['Loan Amount']
df_flexiloansI['Sanctioned Amount'] = ''
df_flexiloansI['PF Charges'] = ''
df_flexiloansI['Doc Charges'] = ''
df_flexiloansI['Insurance Charges'] = ''
df_flexiloansI['Net Disbursed Amount'] = ''
df_flexiloansI['Interest Rate'] = ''
df_flexiloansI['Interest Rate Type'] = ''
df_flexiloansI['Tenure'] = ''
df_flexiloansI['Repayment Frequency'] = ''
df_flexiloansI['Approved Date'] = ''
df_flexiloansI['Disbursed Date'] = ''
df_flexiloansI['Post Sanctioned Status'] = ''
df_flexiloansI['Rejected Reason'] = ''

In [21]:
df_flexiloansR = pd.read_excel(path+'\\FL\\FL.xlsx',sheet_name='Rejected',engine='openpyxl')

In [22]:
df_flexiloansR.head()

,code,business_name,application_no,partner_application_number,lead_code,Post_PD_date,Created,Hot Lead Date,Loan Amount,Total Calls Made,Calls Not Answered,Disbursed Date,Approved Date,Fresh_Top_Up,s1,s2,s3,Rejection_Reason,name,Rejected_Date,platform,MTO,serviceable,Mobile_no,inserted_on
0,65c448470t0vy,NaN,PEF-KABEN-000-FEB24-00376,NaN,65c4480f3puve,NaT,2024-02-08,NaT,50000,NaN,NaN,NaN,NaT,Fresh,Not approved,Lender Rejection,Credit Policy,"[""cre_reject_status""]",Pine Labs,2024-02-08 08:49:45,Web,NaN,0,9972560285,2024-02-08 03:30:13.418
1,65c4480f2wb02,SMS SUPER MART,PNF-KABEN-000-FEB24-00614,65c4456c32406deb8246dc84,65c4480f3puve,NaT,2024-02-08,NaT,1000000,NaN,NaN,NaN,NaT,Fresh,Not approved,Lender Rejection,Credit Policy,"[""cre_reject_status""]",Pine Labs,2024-02-08 08:48:49,Web,1000000.0,0,9972560285,2024-02-08 03:30:13.418
2,65c422e78b00r,L.MARK ENTERPRISES,PEF-TAVIC-000-FEB24-00002,NaN,5e04b98fm9rgz,NaT,2024-02-08,NaT,50000,NaN,NaN,NaN,NaT,Fresh,Not approved,Lender Rejection,Credit Policy,"[""cre_reject_status""]",Pine Labs,2024-02-08 06:10:21,Web,NaN,0,8220360839,2024-02-08 03:30:13.418
3,65c422c53rcwm,L.MARK ENTERPRISES,PEF-TAMAN-000-FEB24-00010,65c41f52b51af8acd97ffb1d,5e04b98fm9rgz,NaT,2024-02-08,NaT,750000,NaN,NaN,NaN,NaT,Fresh,Not approved,Lender Rejection,Credit Policy,"[""cre_reject_status""]",Pine Labs,2024-02-08 06:09:42,Web,1000000.0,0,8220360839,2024-02-08 03:30:13.418
4,65c38cc92b0i5,INCLUSION ACADEMY PRIVATE LIMITED,PNF-DEJAG-000-FEB24-00014,65c38b13c30ec1bd8443f44a,65c38cc9xk5cs,NaT,2024-02-07,NaT,1000000,1.0,0.0,NaN,NaT,Fresh,Not approved,Seller Rejection,Required Documentation not Provided,"[""Document Required""]",Pine Labs,2024-02-07 19:57:38,Web,1000000.0,1,8287781952,2024-02-08 03:30:13.418

In [23]:
df_flexiloansR['Customer ID'] = df_flexiloansR['code']
df_flexiloansR['LAN'] = df_flexiloansR['application_no']
df_flexiloansR['Contact No.'] = df_flexiloansR['Mobile_no']
df_flexiloansR['Lender Partner '] = 'Flexi Loan'
df_flexiloansR['Merchant Name '] = ''
df_flexiloansR['Business Name '] = df_flexiloansR['business_name']
df_flexiloansR['Region'] = ''
df_flexiloansR['State'] = ''
df_flexiloansR['City'] = ''
df_flexiloansR['Final Lead Status'] = df_flexiloansR['s1']
df_flexiloansR['Lead Created Date'] = df_flexiloansR['Created']
df_flexiloansR['Lead last Disposition '] = df_flexiloansR['s3']
df_flexiloansR['Last disposition Date'] = ''
df_flexiloansR['Pendency'] = ''
df_flexiloansR['Monthly turn over of merchant'] = ''
df_flexiloansR['Loan Amount Requested'] = df_flexiloansR['Loan Amount']
df_flexiloansR['Sanctioned Amount'] = ''
df_flexiloansR['PF Charges'] = ''
df_flexiloansR['Doc Charges'] = ''
df_flexiloansR['Insurance Charges'] = ''
df_flexiloansR['Net Disbursed Amount'] = ''
df_flexiloansR['Interest Rate'] = ''
df_flexiloansR['Interest Rate Type'] = ''
df_flexiloansR['Tenure'] = ''
df_flexiloansR['Repayment Frequency'] = ''
df_flexiloansR['Approved Date'] = df_flexiloansR['Approved Date']
df_flexiloansR['Disbursed Date'] = ''
df_flexiloansR['Post Sanctioned Status'] = ''
df_flexiloansR['Rejected Reason'] = np.where(df_flexiloansR['s1']=='Not approved',df_flexiloansR['s2']+" & " + df_flexiloansR['s3'],"")

In [24]:
df_LK_final = df_lendingkart[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [25]:
df_FLA = df_flexiloansA[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [26]:
df_FLR = df_flexiloansR[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [27]:
df_FLI = df_flexiloansI[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason']]

In [28]:
df_FL_final = df_FLA.append(df_FLR).append(df_FLI)

In [29]:
df_FL_final.head()

,Customer ID,LAN,Contact No.,Lender Partner,Merchant Name,Business Name,Region,State,City,Final Lead Status,Lead Created Date,Lead last Disposition,Last disposition Date,Pendency,Monthly turn over of merchant,Loan Amount Requested,Sanctioned Amount,PF Charges,Doc Charges,Insurance Charges,Net Disbursed Amount,Interest Rate,Interest Rate Type,Tenure,Repayment Frequency,Approved Date,Disbursed Date,Post Sanctioned Status,Rejected Reason
0,65aa5abbq6qe1,PNF-PUFEN-000-JAN24-00013,9023315800,Flexi Loan,,ARMAAN SALES CORPORATION,,,,Disbursed,2024-01-19,None,,,,2000000,1500000,2.36,8850,,1414362.0,21.2,Variable,36,Months,2024-01-20 20:47:22,2024-01-25 00:00:00,,
1,6586daf61z5ki,PEF-MAKAL-000-DEC23-00047,8080807039,Flexi Loan,,Vighnesh Trading Company,,,,Disbursed,2023-12-23,None,,,,1500000,1000000,2.36,11800,,961209.0,1.2,Flat,36,Months,2023-12-28 19:24:00,2023-12-30 00:00:00,,
2,658544fbxchuh,PNF-MABAD-000-DEC23-00078,9763996082,Flexi Loan,,vin system,,,,Disbursed,2023-12-22,None,,,,1500000,480000,14160.0,0,,480000.0,2.1667,Flat,36,Months,2024-01-02 18:21:47,2024-01-03 00:00:00,,
3,6571c2a5itkqd,PEF-TALEV-000-DEC23-00001,9629508600,Flexi Loan,,JAI TRADERS,,,,Disbursed,2023-12-07,None,,,,1500000,815000,28851.0,0,,815000.0,1.75,Flat,36,Months,2023-12-15 00:28:42,2023-12-17 00:00:00,,
4,65ae638aj8kej,PEF-KABEN-000-JAN24-00698,8197837814,Flexi Loan,,T S ENTERPRISES,,,,Disbursed,2024-01-22,None,,,,1500000,425000,3.54,5900,,392110.5,2.0,Flat,24,Months,2024-01-29 12:28:40,2024-01-29 00:00:00,,

In [30]:
df_FL_final['Contact No.'].nunique()

964

In [31]:
df_FL_final.shape

(1166, 29)

In [32]:
df_FL_final['Lead Created Date']=df_FL_final['Lead Created Date'].astype('datetime64[ns]')

In [33]:
df_FL_final['Lead Created Date'].dtype

dtype('<M8[ns]')

In [34]:
df_LK_final['Lead Created Date']=df_LK_final['Lead Created Date'].astype('datetime64[ns]')

In [35]:
df_LK_final['Approved Date']=df_LK_final['Approved Date'].astype('datetime64[ns]')

In [36]:
df_FL_final['Sanctioned Amount'].dtype

dtype('O')

In [37]:
df_LK_final['Lead Created Date'].dtype

dtype('<M8[ns]')

In [38]:
df_LK_final['Approved Date'].dtype

dtype('<M8[ns]')

In [39]:
#pd.to_numeric(df_FL_final['Sanctioned Amount'], errors="ignore")
df_FL_final['Sanctioned Amount']=df_FL_final['Sanctioned Amount'].replace('',0).astype(float)
df_FL_final['Sanctioned Amount'].dtype

dtype('float64')

In [40]:
#df_FL_final = df_FL_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[False,False])

In [41]:
df_LK_final['Disbursed Date'].dtype
df_LK_final['Disbursed Date']=pd.to_datetime(df_LK_final['Disbursed Date'])
df_LK_final['Disbursed Date'].dtype
df_FL_final['Disbursed Date'].dtype
df_FL_final['Disbursed Date']=pd.to_datetime(df_FL_final['Disbursed Date'])
df_FL_final['Disbursed Date'].dtype

dtype('<M8[ns]')

In [42]:
df_LK_final['Sanctioned Amount'].dtype

dtype('float64')

In [43]:
#df_LK_final = df_LK_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[False,False])

In [44]:
df_FL_final = df_FL_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[False,False])

In [45]:
df_LK_final = df_LK_final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[False,False])

In [46]:
T = str(((date.today()).strftime("%Y%m%d")))

In [47]:
df_Final = df_FL_final.append(df_LK_final)

In [48]:
#df_Final['Lead Created Date'] =pd.todatetime(df_Final['Lead Created Date'],format="%Y:%M:%D")

In [49]:
#df_Final = df_Final.sort_values(by=['Contact No.','Lead Created Date'],ascending=[True,True])

In [50]:
#adding dicsionary to add one column (Reverse Mapping)
Mapping_dictionary ={'Agreement Signed' : 'Approved' , 'Agreement Stage' : 'Approved' , 'Application in Progress' : 'InComplete Appl' ,'Application Rejected': 'Reject', 'Application under Evaluation' : 'In Process' , 'Approved' : 'Approved' , 
'Closed': 'Reject' , 'Disbursed': 'Disbursed' , 'Fresh Lead': 'New Lead', 'Hot Lead': 'In Process',
 'Not approved':'Reject' ,'Qualified Lead': 'InComplete Appl' ,'Terms & Conditions Stage' : 'Approved'}

#df_Final['Final Status'] = df_Final['Final Lead Status'].map(Mapping_dictionary)

df_Final['Final Status'] = np.where(df_Final['Lead last Disposition ']== "Not Started", 'New Lead',df_Final['Final Lead Status'].map(Mapping_dictionary))
#df_Final['Sanctioned Amount']=df_Final['Sanctioned Amount'].astype(int)
df_Final['Approved Amount']=df_Final['Sanctioned Amount'].div(100000).round(3)

In [51]:
#df_Final['Count']=df_Final.groupby(['Contact No.','Lender Partner '])[['Contact No.']].count()

In [52]:
df_Final.head()

,Customer ID,LAN,Contact No.,Lender Partner,Merchant Name,Business Name,Region,State,City,Final Lead Status,Lead Created Date,Lead last Disposition,Last disposition Date,Pendency,Monthly turn over of merchant,Loan Amount Requested,Sanctioned Amount,PF Charges,Doc Charges,Insurance Charges,Net Disbursed Amount,Interest Rate,Interest Rate Type,Tenure,Repayment Frequency,Approved Date,Disbursed Date,Post Sanctioned Status,Rejected Reason,Final Status,Approved Amount
39,65bcd780julvd,PEF-DEHAS-000-FEB24-00006,9.999401e+09,Flexi Loan,,Primex Laboratories,,,,Approved,2024-02-02,None,,,,400000,500000.0,2.95,5900,,466028.0,1.5,Flat,30,Months,2024-02-07 13:22:27,NaT,,,Approved,5.0
718,6595a84dddwdl,PEF-UTSHI-000-JAN24-00005,9.999361e+09,Flexi Loan,,SABHERWAL ELECTRICALS,,,,Not approved,2024-01-04,Credit Policy,,,,50000,0.0,,,,,,,,,NaT,NaT,,Lender Rejection & Credit Policy,Reject,0.0
719,6595a828smnny,PEF-UTSHI-000-JAN24-00004,9.999361e+09,Flexi Loan,,SABHERWAL ELECTRONICS,,,,Not approved,2024-01-04,Credit Policy,,,,925000,0.0,,,,,,,,,NaT,NaT,,Lender Rejection & Credit Policy,Reject,0.0
81,65bdf53aydgnq,PNF-HAANA-000-FEB24-00004,9.999204e+09,Flexi Loan,,MOHD NASEEM AHMED BOOK BINDER,,,,Not approved,2024-02-03,Not Interested,,,,50000,0.0,,,,,,,,,NaT,NaT,,Seller Rejection & Not Interested,Reject,0.0
107,65ba17aca0ztu,NaN,9.999165e+09,Flexi Loan,,TD EXPORT,,,,Closed,2024-01-31,Lender Reject in last 90 days,,,,50000,0.0,,,,,,,,,NaT,NaT,,,Reject,0.0

In [53]:
df_Final.dtypes

Customer ID                              object
LAN                                      object
Contact No.                             float64
Lender Partner                           object
Merchant Name                            object
Business Name                            object
Region                                   object
State                                    object
City                                     object
Final Lead Status                        object
Lead Created Date                datetime64[ns]
Lead last Disposition                    object
Last disposition Date                    object
Pendency                                 object
Monthly turn over of merchant            object
Loan Amount Requested                     int64
Sanctioned Amount                       float64
PF Charges                               object
Doc Charges                              object
Insurance Charges                        object
Net Disbursed Amount                     object
Interest Rate                            object
Interest Rate Type                       object
Tenure                                   object
Repayment Frequency                      object
Approved Date                            object
Disbursed Date                   datetime64[ns]
Post Sanctioned Status                   object
Rejected Reason                          object
Final Status                             object
Approved Amount                         float64
dtype: object

In [54]:
df_Indifi= pd.read_csv(path+'\\Indifi\\applications.csv')

In [55]:
df_Indifi.head()

,request_id,id,name,phone,anchor_unique_id,anchor,city,location,applied_amount,state,lead_date,lead_time,application_date,application_time,sanction_amount,sanction_date,sanction_time,disbursed_amount,disbursed_date,disbursed_time,interest_rate,processing_fee,rejection_date,rejection_time,rejection_reason,utm_source,utm_campaign,utm_medium,is_renewed,business_nature,anchor_applicationid,application_completion_date,application_completion_time,is_womenled,fast_loan_link,rejection_code,dsa_agent_id
0,7255662,1dfdb340-f774-4a93-a528-be7f4b46e108,OPALO VENTURE,9.497046e+09,NaN,Pinelabs,NaN,NaN,1000000.0,Rejected,07-02-2024,10:43,07-02-2024,10:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-02-2024,10:29,Credit Risk Assessment,'---,'---,'---,False,NaN,NaN,NaN,NaN,NaN,'-,credit_reject,NaN
1,7255019,fa862140-403f-42fa-af93-76f7b4b74665,APPLE GARAGE,8.408000e+09,{65c388ddc30ec1bd8443f42f},Pinelabs,Panipat,Haryana,NaN,Incomplete,07-02-2024,07:11,07-02-2024,07:18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,NaN,NaN,NaN,'-,NaN,NaN
2,7254919,ed0d2dc1-b3e8-4eb7-a429-2e4deac00ef1,VIJAY COMPUTERS(COMPUTER SALES & SERVICES),9.822857e+09,NaN,Pinelabs,Aurangabad,Maharashtra,0.0,Incomplete,07-02-2024,06:29,07-02-2024,06:59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'---,'---,'---,False,NaN,NaN,NaN,NaN,NaN,'-,NaN,NaN
3,7254593,5a51c8bc-9e2a-4698-97d8-7d25e8845c31,Red apple mobiles,9.686860e+09,NaN,Pinelabs,NaN,NaN,50000.0,Incomplete,07-02-2024,05:50,07-02-2024,05:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,'---,'---,'---,False,NaN,NaN,NaN,NaN,NaN,'-,NaN,NaN
4,7254451,1b85f98e-1271-4c07-b4af-709737523fac,K N S FURNITURE AND FURNISHING,9.886579e+09,NaN,Pinelabs,NaN,NaN,1500000.0,Rejected,07-02-2024,05:26,07-02-2024,05:45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-02-2024,05:46,Credit Risk Assessment,'---,'---,'---,False,NaN,NaN,NaN,NaN,NaN,'-,credit_reject,NaN

In [56]:
df_Indifi.columns

Index(['request_id', 'id', 'name', 'phone', 'anchor_unique_id', 'anchor',
       'city', 'location', 'applied_amount', 'state', 'lead_date', 'lead_time',
       'application_date', 'application_time', 'sanction_amount',
       'sanction_date', 'sanction_time', 'disbursed_amount', 'disbursed_date',
       'disbursed_time', 'interest_rate', 'processing_fee', 'rejection_date',
       'rejection_time', 'rejection_reason', 'utm_source', 'utm_campaign',
       'utm_medium', 'is_renewed', 'business_nature', 'anchor_applicationid',
       'application_completion_date', 'application_completion_time',
       'is_womenled', 'fast_loan_link', 'rejection_code', 'dsa_agent_id'],
      dtype='object')

In [57]:
df_Indifi.dtypes

request_id                       int64
id                              object
name                            object
phone                          float64
anchor_unique_id                object
anchor                          object
city                            object
location                        object
applied_amount                 float64
state                           object
lead_date                       object
lead_time                       object
application_date                object
application_time                object
sanction_amount                float64
sanction_date                   object
sanction_time                   object
disbursed_amount               float64
disbursed_date                  object
disbursed_time                  object
interest_rate                  float64
processing_fee                 float64
rejection_date                  object
rejection_time                  object
rejection_reason                object
utm_source                      object
utm_campaign                    object
utm_medium                      object
is_renewed                        bool
business_nature                 object
anchor_applicationid           float64
application_completion_date     object
application_completion_time     object
is_womenled                    float64
fast_loan_link                  object
rejection_code                  object
dsa_agent_id                   float64
dtype: object

In [58]:
df_Indifi[df_Indifi['disbursed_date'].notnull()].head(10)

,request_id,id,name,phone,anchor_unique_id,anchor,city,location,applied_amount,state,lead_date,lead_time,application_date,application_time,sanction_amount,sanction_date,sanction_time,disbursed_amount,disbursed_date,disbursed_time,interest_rate,processing_fee,rejection_date,rejection_time,rejection_reason,utm_source,utm_campaign,utm_medium,is_renewed,business_nature,anchor_applicationid,application_completion_date,application_completion_time,is_womenled,fast_loan_link,rejection_code,dsa_agent_id
75,7196038,7a9fecf5-6db5-4155-8a49-697082d4790e,KAMALNAYAN MOBILE SHOPEE,9.860117e+09,"{02496237,0}",Pinelabs,NAGPUR,Maharashtra,350000.0,Loan Active,31-01-2024,08:16,31-01-2024,08:16,355411.0,03-02-2024,12:07,355411.0,07-02-2024,07:14,32.0,16733.46,NaN,NaN,NaN,'---,'---,'---,True,Retail,NaN,02-02-2024,04:24,NaN,'-,NaN,NaN
119,7176890,e1b05852-9b56-4093-8ae1-a03f3542e8ca,U.K TELECOM,9.837687e+09,{00},Pinelabs,Haridwar,Uttarakhand,145000.0,Loan Active,27-01-2024,02:07,27-01-2024,02:20,147241.0,31-01-2024,12:52,147241.0,31-01-2024,05:00,27.0,6949.78,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,30-01-2024,01:40,NaN,'-,NaN,NaN
135,7170159,cd2e9399-b151-4429-ac68-f96d8f4e1ea9,Mobicity,7.002828e+09,{00},Pinelabs,Thane,Maharashtra,1200000.0,Loan Active,25-01-2024,06:37,25-01-2024,06:37,1218552.0,27-01-2024,06:44,1218552.0,29-01-2024,07:17,27.0,35803.49,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,25-01-2024,07:45,NaN,'-,NaN,NaN
140,7168231,2ee603eb-e204-49f9-86ab-52d62beb8c26,PANKHOODI COLLECTION,9.829143e+09,{00},Pinelabs,Jaipur,Rajasthan,300000.0,Loan Active,25-01-2024,12:24,25-01-2024,01:38,304638.0,27-01-2024,06:17,304638.0,30-01-2024,07:23,23.0,14342.97,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,25-01-2024,04:07,NaN,'-,NaN,NaN
170,7155104,618dd7d6-e3ca-4bbb-878c-ca4ee371f022,MILLENNIUM VENTURES,9.971400e+09,{00},Pinelabs,Faridabad,Haryana,99000.0,Loan Active,23-01-2024,06:04,23-01-2024,06:53,100531.0,27-01-2024,04:32,100531.0,30-01-2024,05:24,35.0,4733.20,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,25-01-2024,05:59,NaN,'-,NaN,NaN
173,7153896,6f3f5ef9-3623-4e48-87a5-9ccd7a5aa18f,BALA SUPER SHOP,7.358499e+09,{00},Pinelabs,Chennai,Tamil Nadu,2000000.0,Loan Active,23-01-2024,03:55,23-01-2024,03:55,1000000.0,30-01-2024,05:11,1000000.0,03-02-2024,05:00,21.0,47200.00,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,25-01-2024,03:58,NaN,'-,NaN,NaN
245,7112759,e67cfc6b-e03a-45ae-a5a4-7cc2f82157a2,KGN MOBILE TELECOM,9.729553e+09,"{00,65a79bf0dad955d682c70996}",Pinelabs,Faridabad,Haryana,373000.0,Loan Active,17-01-2024,02:51,17-01-2024,03:04,378767.0,29-01-2024,04:07,378767.0,31-01-2024,06:41,24.0,13363.66,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,18-01-2024,12:07,NaN,'-,NaN,NaN
308,7075576,ccc22376-3e1c-4b57-9b8b-54ec9c869e6a,CREATIVE POWER SOLUTION,9.943990e+09,{00},Pinelabs,Coimbatore,Tamil Nadu,1634000.0,Loan Active,12-01-2024,07:51,12-01-2024,07:27,1634000.0,20-01-2024,11:35,1634000.0,30-01-2024,05:00,21.0,67291.39,NaN,NaN,NaN,'---,'---,'---,False,Trading,NaN,18-01-2024,10:37,NaN,'-,NaN,NaN
368,7055715,e04beb18-6fd7-46b0-9cb1-caffc536c967,MY PLANET SHOP,9.007874e+09,"{00,659e9d49ad5623e931c34ad9}",Pinelabs,North 24 Parganas,West Bengal,1714000.0,Loan Active,10-01-2024,07:35,10-01-2024,07:35,588967.0,15-01-2024,11:59,588967.0,17-01-2024,02:57,21.0,20779.93,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,11-01-2024,02:02,NaN,'-,NaN,NaN
373,7054307,57802980-8085-4086-befa-1b06cb443dc3,AR Mobiles & Electronics,6.369522e+09,{00},Pinelabs,Pudukkottai,Tamil Nadu,198000.0,Loan Active,10-01-2024,05:11,10-01-2024,05:02,201061.0,11-01-2024,02:30,201061.0,17-01-2024,11:54,34.0,9466.35,NaN,NaN,NaN,'---,'---,'---,False,Retail,NaN,10-01-2024,05:14,NaN,'-,NaN,NaN

In [59]:
Mapping_dictionary_Indifi ={'Documentation Pending' : 'Approved' , 'Incomplete' : 'InComplete Appl' , 'Loan Active' : 'Disbursed' ,'Offer Acceptance Pending': 'Approved', 'Processing For Offer' : 'In Process' , 'Rejected' : 'Reject' , 
'Withdrawn': 'Reject','Ready To Disburse':'Approved','Under Review For Offer':'In Process'}

In [60]:
df_Indifi['Customer ID'] = df_Indifi['anchor_unique_id']
df_Indifi['LAN'] = df_Indifi['request_id']
df_Indifi['Contact No.'] = df_Indifi['phone']
df_Indifi['Lender Partner '] = 'INDIFI'
df_Indifi['Merchant Name '] = ''
df_Indifi['Business Name '] = df_Indifi['name']
df_Indifi['Region'] = ''
df_Indifi['State'] = df_Indifi['location']
df_Indifi['City'] = df_Indifi['city']
df_Indifi['Final Lead Status'] =df_Indifi['state']
df_Indifi['Lead Created Date'] = df_Indifi['lead_date']
df_Indifi['Lead last Disposition '] =df_Indifi['state']
df_Indifi['Last disposition Date'] =df_Indifi['application_completion_date']
df_Indifi['Pendency'] =''
df_Indifi['Monthly turn over of merchant'] = ''
df_Indifi['Loan Amount Requested'] = df_Indifi['applied_amount']
df_Indifi['Sanctioned Amount'] =df_Indifi['sanction_amount']
df_Indifi['PF Charges'] =''
df_Indifi['Doc Charges'] = ''
df_Indifi['Insurance Charges'] = ''
df_Indifi['Net Disbursed Amount'] =df_Indifi['disbursed_amount']
df_Indifi['Interest Rate'] = df_Indifi['interest_rate']
df_Indifi['Interest Rate Type'] = ''
df_Indifi['Tenure'] =''
df_Indifi['Repayment Frequency'] = ''
df_Indifi['Approved Date'] =df_Indifi['sanction_date']
df_Indifi['Disbursed Date'] =df_Indifi['disbursed_date']
df_Indifi['Post Sanctioned Status'] = ''
df_Indifi['Rejected Reason'] =df_Indifi['rejection_reason']
df_Indifi['Final Status']=df_Indifi['state'].map(Mapping_dictionary_Indifi)
df_Indifi['Sanctioned Amount'] = pd.to_numeric(df_Indifi['Sanctioned Amount'], errors='coerce')
df_Indifi['Approved Amount']=df_Indifi['Sanctioned Amount'].div(100000).round(3)
df_Indifi['lead_time']=df_Indifi['lead_time']

In [61]:
df_Indifi_final=df_Indifi[['Customer ID', 'LAN',
       'Contact No.', 'Lender Partner ', 'Merchant Name ', 'Business Name ',
       'Region', 'State', 'City', 'Final Lead Status', 'Lead Created Date',
       'Lead last Disposition ', 'Last disposition Date', 'Pendency',
       'Monthly turn over of merchant', 'Loan Amount Requested',
       'Sanctioned Amount', 'PF Charges', 'Doc Charges', 'Insurance Charges',
       'Net Disbursed Amount', 'Interest Rate', 'Interest Rate Type', 'Tenure',
       'Repayment Frequency', 'Approved Date', 'Disbursed Date',
       'Post Sanctioned Status', 'Rejected Reason','Final Status','Approved Amount','lead_time']]

In [62]:
df_Indifi_final.dtypes

Customer ID                       object
LAN                                int64
Contact No.                      float64
Lender Partner                    object
Merchant Name                     object
Business Name                     object
Region                            object
State                             object
City                              object
Final Lead Status                 object
Lead Created Date                 object
Lead last Disposition             object
Last disposition Date             object
Pendency                          object
Monthly turn over of merchant     object
Loan Amount Requested            float64
Sanctioned Amount                float64
PF Charges                        object
Doc Charges                       object
Insurance Charges                 object
Net Disbursed Amount             float64
Interest Rate                    float64
Interest Rate Type                object
Tenure                            object
Repayment Frequency               object
Approved Date                     object
Disbursed Date                    object
Post Sanctioned Status            object
Rejected Reason                   object
Final Status                      object
Approved Amount                  float64
lead_time                         object
dtype: object

In [63]:
#df_Indifi_final['Disbursed Date']=df_Indifi_final['Disbursed Date'].astype('datetime64[ns]')

In [64]:
df_Indifi_final['Disbursed Date'] = pd.to_datetime(df_Indifi_final['Disbursed Date'].str.slice(6,10)+'-'+df_Indifi_final['Disbursed Date'].str.slice(3,5)+'-'+df_Indifi_final['Disbursed Date'].str.slice(0,2))

In [65]:
df_Indifi_final['Disbursed Date']=pd.to_datetime(df_Indifi_final['Disbursed Date'], errors='coerce')

In [66]:
df_Indifi_final['Lead Created Date'] = pd.to_datetime(df_Indifi_final['Lead Created Date'].str.slice(6,10)+'-'+df_Indifi_final['Lead Created Date'].str.slice(3,5)+'-'+df_Indifi_final['Lead Created Date'].str.slice(0,2))

In [67]:
df_Indifi_final['Lead Created Date']=pd.to_datetime(df_Indifi_final['Lead Created Date'], errors='coerce')

In [68]:
df_Indifi_final['Approved Date'] = pd.to_datetime(df_Indifi_final['Approved Date'].str.slice(6,10)+'-'+df_Indifi_final['Approved Date'].str.slice(3,5)+'-'+df_Indifi_final['Approved Date'].str.slice(0,2))

In [69]:
df_Indifi_final['Approved Date']=pd.to_datetime(df_Indifi_final['Approved Date'], errors='coerce')

In [70]:
df_Indifi_final['Loan Amount Requested']=df_Indifi_final['Loan Amount Requested'].astype('Int64',errors='ignore')

In [71]:
df_Indifi_final['Net Disbursed Amount']=df_Indifi_final['Net Disbursed Amount'].astype(object)

In [72]:
df_Indifi_final['Interest Rate']=df_Indifi_final['Interest Rate'].astype(object)

In [73]:
df_Indifi_final.dtypes

Customer ID                              object
LAN                                       int64
Contact No.                             float64
Lender Partner                           object
Merchant Name                            object
Business Name                            object
Region                                   object
State                                    object
City                                     object
Final Lead Status                        object
Lead Created Date                datetime64[ns]
Lead last Disposition                    object
Last disposition Date                    object
Pendency                                 object
Monthly turn over of merchant            object
Loan Amount Requested                     Int64
Sanctioned Amount                       float64
PF Charges                               object
Doc Charges                              object
Insurance Charges                        object
Net Disbursed Amount                     object
Interest Rate                            object
Interest Rate Type                       object
Tenure                                   object
Repayment Frequency                      object
Approved Date                    datetime64[ns]
Disbursed Date                   datetime64[ns]
Post Sanctioned Status                   object
Rejected Reason                          object
Final Status                             object
Approved Amount                         float64
lead_time                                object
dtype: object

In [74]:
df_Indifi_final = df_Indifi_final.sort_values(by=['Contact No.','Lead Created Date','lead_time'],ascending=[False,False,False])

In [75]:
df_Final = df_Final.append(df_Indifi_final)

In [76]:
path = os.getcwd()

In [77]:
path

'C:\\Users\\Tithi Hunka\\OneDrive - Pine Labs Private Limited\\TermLoans Code_Dummy'

In [78]:
df_Final.to_excel(path+'\\Output\\Consolidated(LK_FL_Indifi)'+ T+'.xlsx',index=False)